### PR TITLE
include the filter if not already

### PR DESCRIPTION
**Pull request by mburns**
I saw this code commented out, so I tried rewriting it.

[reference](http://stackoverflow.com/questions/14004325/add-element-to-an-array-if-its-not-there-already)

### CODE REVIEW

**Comment by drenalin23** [comment]
+1

**Comment by jguice** [comment]
Yeah I'm not sure if those are needed, but was the pattern from the original code (my hope was that it would work without and I could just remove the commented portions).

I think your rewrite has a different behavior than the original though.

#### original
```diff
-# unless node['repose']['filters'].include? 'extract-device-id'
-#   filters = node['repose']['filters'] + ['extract-device-id']
-#   node.normal['repose']['filters'] = filters
-# end
```
**behavior:** if the filters list doesn't include 'extract-device-id', add it to the original list and set the next-level higher attribute precedence to the updated list (to override the previous filter list).

#### rewrite
```diff
+# add only if it doesn't already exist
+node.set['repose']['filters'] |= %w(extract-device-id)
```
**behavior:** if the filter list is not set, set it to just ['extract-device-id']

--

I think the original author's intent was *if you include the recipe for a particular filter, ensure that filter is actually part of the filters attribute list* (which ultimately causes the filter to be loaded by repose on startup).

In our case we both include the recipe and add the filter to the list in every case (and there might be a case where I'd want to configure a filter but not actually load it yet).  I also just didn't like the manipulation of attributes any more than required. :wink:

**Comment by mburns** [comment]
I agree with you on the author's intent. I think my changes aren't so far off.

>if the filter list is not set, set it to just ['extract-device-id']

Both methods behave this way.

So we have 2 steps that need to happen:

1. if the specific filter name (`'extract-device-id'`) isn't a member in the `filters` list, add it, regardless of if the list is empty or not.

    The `|=` only adds an element if it is not already an element in the array:

    ```ruby
    irb(main):002:0> a = %w()
    => []
    irb(main):004:0> a |= %w(foo)     # adds 'foo'
    => ["foo"]
    irb(main):005:0> a |= %w(bar)     # adds 'bar'
    => ["foo", "bar"]
    irb(main):006:0> a |= %w(foo)     # doesn't add redundant element 'foo'
    => ["foo", "bar"]
    ```
2. 'save' the new list.

    `node.set` is equivalent to `node.normal`, though `node.set` is the 'old' way that I use in recipes out of habit.

I should test this in the VM to make sure, but I think they are trying to do the same thing.

**Comment by jguice** [comment]
Ah!  Didn't catch that you were doing bitwise OR instead of logical. :wink:

**Pull request closed without merging**
