### PR TITLE
feat(upstart): switch from runit to upstart

### PR DESCRIPTION
**Pull request by jguice**

### CODE REVIEW

**Comment by jguice** [comment]
This is going to require some manual steps to deploy (e.g. shutting down runit repose-valve and disabling)

**Comment by jguice** [comment]
Might want to remove the package-installed /etc/init.d file too to avoid confusion too.

**Comment by mburns** [comment]
1 rubocop complaint, then :+1:

**Comment by jguice** [comment]
## deploy steps
- take region offline via loadbalancer script
- `sv stop repose-valve`
- `kill -9` any lingering repose-valve.jar processes
- `rm /etc/service/repose-valve`
- `rm -rf /service/repose-valve`
- run `chef-client`

Should see repose running via upstart...e.g:
```
$ service repose-valve status
repose-valve start/running, process 32712
```

Log should be writing to `/var/log/upstart/repose-valve.log` and the usual `/var/log/repose/current.log`

**Comment by mburns** [comment]
plan sounds good to me.

**Pull request merged**
