### PR TITLE
fix(OOM): increase heap to resolve mem issue

### PR DESCRIPTION
**Pull request by jguice**
If it comes back again it's likely a leak :(

### CODE REVIEW

**Comment by mburns** [comment]
wfm :+1:

**Comment by tpboudreau-rackspace** [comment]
if we hit 1GB of memory, it must be a leak.

**Comment by jguice** [comment]
Yeah, keeps happening...I was just adding `-XX:-UseConcMarkSweepGC` should I move the memory back down?

**Comment by jguice** [comment]
Are you able to hop on VPN and take a look?  Repose is crashing frequently. :disappointed:

**Comment by jguice** [comment]
well, moving ahead with this to at least space out the crashes ;)

**Comment by tpboudreau-rackspace** [comment]
Sorry, went off to do something else.  

Crashing frequently?  Not desirable.

I suspect it's both a leak and that it's in the extract-device-id filter -- we're the only user -- any other fitler (except perhaps Valkyrie which is newish) would have long since been fixed.

**Comment by jguice** [comment]
Oddly enough it subsides as quickly and abruptly as it started.  These changes are 0.2.16 and in chef master ready for deploy.

I didn't actually push them though since it started working.

**Pull request merged**
